### ISSUE TITLE
0.2 alpha 1st tryout

### ISSUE THREAD

**Issue by lo5tinpr0** [Noc2/Chiota#1]
Hey everybody, if you want to test the second version of the app with me, that's my addresss: 
I would be happy about some chats!

KXJQXBRUBODDYWNLZASEWKGMRXODVVRTPKHXOPEHCR9EMNRVGODJELRFBKVRDUYTKAHQG99QRCVZHBUIZ

![photo_2018-04-02_14-44-10](https://user-images.githubusercontent.com/37935152/38196656-931e3c18-3684-11e8-9d87-098e3a2dc6ae.jpg)

**Comment by Noc2** [comment]
Thanks for testing the app. I just send you a contact request. I will try to implement notifications in the next release because otherwise, you don’t see that you got a contact request 😉.

**Comment by lo5tinpr0** [comment]
Sry for the delayed response, everything else via Chiota ;)
