### ISSUE TITLE
Invalid address, try again

### ISSUE THREAD

**Issue by nickvetter** [Noc2/Chiota#8]
If i want to add a new scaned contact to the list of contacts, an exception "Invalid address, try again" was thrown. Here are my settings:
1. Android 8.0 (hornor 9 lite)
2. Node: default https://field.carriota.com:443
3. chiota installed as a beta app from google app store

**Comment by Noc2** [comment]
Can you test if you also get this problem when you try to add me (OZQQEPQ9AH9QUX9BQAWOBCTZNAFIFYYWMZUDKFUKGQAIEFAXBZKWCMMOXFU9PDCAMAHDIUTCZPZK9RKPZ) because the issue is usually caused by an invalid address created by the other device (so that app should work fine on your side)? Apart from that I really hope to publish a new version in the coming days/since I changed quite a bit of the underlying structure.

**Comment by nickvetter** [comment]
Hi David, I tried it. Not sure if I understand it right but if the generate address is not verified at that time  get this error. But OK it worked. So please close that issue.

Here some motivation from my side:

A chat using IOTA is a fantastic idea. There is still a lot of work to do, but if it is possible to use the smartphone contacts like WhatsApp it will become really great.

About me:

I am also a software develop. In our team we also using C# .NetStandard 2.0 and Xamarin to create an application for Android, IOs and with latest release and future releases of Xamarin also WPF (Windows) and GTK(Linux) and Mac. 

So hope that IOTA will become standard for iot.

Best Regards

     Nick Vetter


-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 22.06.18, 16:36, David Hawig <notifications@github.com> schrieb:
Can you test if you also get this problem when you try to add me (OZQQEPQ9AH9QUX9BQAWOBCTZNAFIFYYWMZUDKFUKGQAIEFAXBZKWCMMOXFU9PDCAMAHDIUTCZPZK9RKPZ) because the issue is usually caused by an invalid address created by the other device (so that app should work fine on your side)? Apart from that I really hope to publish a new version in the coming days/since I changed quite a bit of the underlying structure.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/Noc2/Chiota/issues/8#issuecomment-399464359","url":"https://github.com/Noc2/Chiota/issues/8#issuecomment-399464359","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Noc2/Chiota","title":"Noc2/Chiota","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Noc2/Chiota"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Noc2 in #8: Can you test if you also get this problem when you try to add me (OZQQEPQ9AH9QUX9BQAWOBCTZNAFIFYYWMZUDKFUKGQAIEFAXBZKWCMMOXFU9PDCAMAHDIUTCZPZK9RKPZ) because the issue is usually caused by an invalid address created by the other device (so that app should work fine on your side)? Apart from that I really hope to publish a new version in the coming days/since I changed quite a bit of the underlying structure.   "}],"action":{"name":"View Issue","url":"https://github.com/Noc2/Chiota/issues/8#issuecomment-399464359"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Noc2/Chiota] Invalid address, try again (#8)",
"sections": [
{
"text": "",
"activityTitle": "**David Hawig**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Noc2",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Noc2/Chiota\",\n\"issueId\": 8,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Noc2/Chiota\",\n\"issueId\": 8\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Noc2/Chiota/issues/8#issuecomment-399464359"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349002077\n}"
}
],
"themeColor": "26292E"
}

**Comment by Noc2** [comment]
Awesome. I would like to get in contact with you. Maybe we can help each other. You can contact me on linkedin https://www.linkedin.com/in/david-hawig-206a44b1/ or via Mail (david.hawig[at]pact[dot]care). Or of course on discord Noc2#4736
