### ISSUE TITLE
Decoding 65 char failed

### ISSUE THREAD

**Issue by alberk8** [Noc2/Chiota#9]
I am testing the Encryption and Decryption using NTRUParamSets.APR2011439FAST and it can encode a string of 65 characters but will throw ""Invalid message encoding!" when decoding.  

It works when the plain text is less then 65 characters.  Possible bug in the NTRUEncrypt ?

**Comment by Noc2** [comment]
Thanks for reaching out. First of all, I quickly updated the wiki article code here (sorry for the old version): https://github.com/Noc2/Chiota/wiki/NTRU-Key-Exchange-for-IOTA
I also tested some longer messages, on my side everything seems to work (see image) fine. 
 
![image](https://user-images.githubusercontent.com/24638510/42310643-3c635406-803c-11e8-8a6c-30b2f4d536eb.png)

If you haven’t, please take a look at my NTRUKex class, here https://github.com/Noc2/Chiota/blob/master/Chiota/Chiota/Services/NTRUKex.cs
And let me know if you still have issues.

**Comment by alberk8** [comment]
Thank you for the reply.  It is my bad.  I have changed the NTRUParamSets but not the maxSize and maxEncrytionSize.  The correct ones should be as below.

```
static int maxEncryptionSize = 604;
static int maxSize = 64;
static NTRUParameters ntruParameters = NTRUParamSets.APR2011439FAST;
```
